apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prom-test
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: kube-prometheus-stack-prometheus
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  ruleSelector: {}
