# ArgoCD Helm values — 로컬 환경
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.127.0.0.1
    tls:
      - hosts:
          - argocd.127.0.0.1
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
