replicaCount: 3

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  cpu: 50

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
  interval: 15s