apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
spec:
  project: default
  source:
    chart: chaos-mesh
    repoURL: https://charts.chaos-mesh.org
    targetRevision: 2.6.3
    helm:
      skipCrds: true
      values: |
        chaosDaemon:
          runtime: containerd
          socketPath: /run/containerd/containerd.sock
        dashboard:
          create: true
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - name: chaos.INGRESS_IP.nip.io
                tls: false
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
spec:
  project: default
  source:
    chart: chaos-mesh
    repoURL: https://charts.chaos-mesh.org
    targetRevision: 2.6.3
    helm:
      values: |
        chaosDaemon:
          runtime: containerd
          socketPath: /run/containerd/containerd.sock
        dashboard:
          create: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaos-dashboard-ingress
  namespace: chaos-mesh
spec:
  ingressClassName: nginx
  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chaos-dashboard
                port:
                  number: 2333
                  