prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    retention: 7d
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    secrets:
      - podinfo-alert-discord-webhook
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by:
        - namespace
        - service
        - severity
        - alertname
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 30m
      receiver: blackhole
      routes:
        - receiver: podinfo-discord
          matchers:
            - service = "podinfo"
    receivers:
      - name: blackhole
      - name: podinfo-discord
        discord_configs:
          - send_resolved: true
            webhook_url_file: /etc/alertmanager/secrets/podinfo-alert-discord-webhook
            title: '{{ .CommonLabels.alertname }}'
            message: |
              [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }}

              severity: {{ .CommonLabels.severity }}
              namespace: {{ .CommonLabels.namespace }}
              service: {{ .CommonLabels.service }}

              {{ .CommonAnnotations.description }}

grafana:
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: 
      - grafana.example.com
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
