apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: chaos-mesh
    repoURL: https://charts.chaos-mesh.org
    targetRevision: 2.6.3
    helm:
      values: |
        installCRDs: true
        controllerManager:
          enabled: false
        chaosDaemon:
          enabled: false
        dashboard:
          create: false
        dnsServer:
          create: false
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true