apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: 6.7.0
    helm:
      values: |
        replicaCount: 3
        service:
          type: ClusterIP
        hpa:
          enabled: true
          maxReplicas: 10
          cpu: 80
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        faults:
          delay: 0
          error: 0
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: podinfo.34.64.241.165.nip.io
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: podinfo-pdb
  namespace: podinfo
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo