apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.5.0
    helm:
      # values: | 뒤에는 정확히 동일한 간격의 공백을 사용해야 합니다.
      values: |
        grafana:
          service:
            type: ClusterIP
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.monitoring.svc.cluster.local:3100
              access: proxy
        prometheus:
          prometheusSpec:
            scrapeInterval: 15s
        alertmanager:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true